# -*- coding: utf-8 -*-
#
# Programming Qt for Symbian^3 Devices documentation build configuration file, created by
# sphinx-quickstart on Fri Jul  8 08:24:25 2011.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.

extensions = ['sphinx.ext.todo', 'sphinx.ext.extlinks', 'sphinx.ext.pngmath',
              'qtextensions.dita']

# setup sphinx.ext.todo
# Enable todos
todo_include_todos = True

# setup sphinx.ext.extlinks (see http://sphinx.pocoo.org/latest/ext/extlinks.html)

# Sample Usage

# :qt:`QPushButton <qpushbutton.html>`
# :creator:`Qt Creator User Interface <creator-quick-tour.html>`
# :mobility:`Connectivity <connectivity-api.html>`
# :component:`ApplicationWindow <qml-applicationwindow.html>`

extlinks = {
    'sdk': ('http://doc.qt.digia.com/sdk-1.1/%s', None),
    'simulator': ('http://doc.qt.digia.com/qtsimulator/%s', None),
    'qt': ('http://qt-project.org/doc/qt-4.8/%s', None),
    'qt5': ('http://qt-project.org/doc/qt-5.0/%s', None),
    'qt5-snapshot': ('http://doc-snapshot.qt-project.org/%s', None),
    'guides-homepage': ('http://qt-project.org/wiki/Developer-Guides/%s', None),
    'download': ('http://releases.qt-project.org/learning/developerguides/%s', None),
    'qtquick-repo': ('http://qt-project.org/doc/qt-4.8/%s', None),
    'creator': ('http://qt-project.org/doc/qtcreator-2.6/%s', None),
    'mobility': ('http://doc.qt.digia.com/qtmobility/%s', None),
    'component': ('http://doc.qt.digia.com/qtquick-components-symbian-1.0/%s', None),
    'component11': ('http://doc.qt.digia.com/qtquick-components-symbian-1.1/%s', None),
    'installer': ('http://doc.qt.digia.com/smart-installer/%s', None),
    }


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'project'
copyright = u'(C) 2012 Digia. http://qt.digia.com'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# NOTE: this is default version which is used if you do now define version in the conf.py inside of the project
#
# The short X.Y version.
version = '0.1'
# The full version, including alpha/beta/rc tags.
release = '0.1 (default)'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'qtweb'
#html_style = 'sphinxdoc.css'


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
	# override theme mail address
	# 'feedback_mail': 'jurgen.bocklage-ryannel@nokia.com'
}

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = ['../themes/']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = 'html_title'

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = 'html_short_title'

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
       '**': ['globaltoc.html', 'localtoc.html', 'sourcelink.html'],
}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
html_domain_indices = False

# If false, no index is generated.
html_use_index = True

# If true, the index is split into individual pages for each letter.
html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

html_add_permalinks = True

# Output file base name for HTML help builder.
htmlhelp_basename = 'htmlhelp_basename'


# -- Options for LaTeX output --------------------------------------------------

# The paper size ('letter' or 'a4').
latex_paper_size = 'a4'

# The font size ('10pt', '11pt' or '12pt').
latex_font_size = '12pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'latex_document.tex', u'title in latex_docuements',
   u'(C) 2012 Digia. http://qt.digia.com/Product/Learning', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = False

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
latex_show_urls = 'footnote'

# Additional stuff for the LaTeX preamble.
#latex_preamble = ''

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = False

# latex_custom_preamble = """
# \\definecolor{VerbatimColor}{rgb}{1.0,1.0,0.9}
# \\definecolor{VerbatimBorderColor}{rgb}{1.0,1.0,0.5}
# """
# latex_elements = {
#   'pointsize': '10pt',
#   'preamble': latex_custom_preamble
# }

# Removes the blank pages betweeen chapters
latex_elements = {
  'classoptions': ',oneside',
  'babel': '\\usepackage[english]{babel}',
  'fncychap': '\\usepackage[Sonny]{fncychap}'
}

# change the font size of the code samples in the LaTex and PDF output
# taken from http://stackoverflow.com/questions/9899283/how-do-you-change-the-code-example-font-size-in-latex-pdf-output-with-sphinx
#
from sphinx.highlighting import PygmentsBridge
from pygments.formatters.latex import LatexFormatter
class CustomLatexFormatter(LatexFormatter):
    def __init__(self, **options):
        super(CustomLatexFormatter, self).__init__(**options)
        self.verboptions = r"formatcom=\footnotesize"
PygmentsBridge.latex_formatter = CustomLatexFormatter


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'document_man_pages', u'title in man_pages',
     [u'(C) 2011 Digia. http://qt.digia.com/Product/Learning'], 1)
]


# -- Options for Epub output ---------------------------------------------------

# The basename for the epub file. It defaults to the project name w/o spaces
epub_basename = 'document_epub_basename'

# Bibliographic Dublin Core info.
epub_title = u'epub_title'
epub_author = u'Digia, Qt Learning'
epub_publisher = u'http://qt.digia.com/Product/Learning/'
epub_copyright = u'(C) 2011 Nokia'

# The language of the text. It defaults to the language option
# or en if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
#epub_exclude_files = []

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# -- Options for Qt Help output ---------------------------------------------------
# The basename for the Qt help file. It defaults to the project name w/o spaces
qthelp_basename = 'qthelp_basename'

